import { Activity, AlertTriangle, Award, Briefcase, FileText, UserCircle, Users } from 'lucide-react';

export const PARENT_TABLE = 'thong_tin_quan_nhan';

export const TABLES = [
  {
    id: PARENT_TABLE,
    label: 'Thông tin nhân sự',
    icon: UserCircle,
    isParent: true,
    columns: [
      'ma_dinh_danh',
      'ho_va_ten_khai_sinh',
      'ngay_thang_nam_sinh',
      'don_vi',
      'dien_bo_tri',
      'gioi_tinh',
      'thang_nam_vao_quan_doi',
      'thang_nam_ve_khoa_cong_tac',
      'so_cmtqd',
      'ngay_cap_cmtqd',
      'noi_cap_cmtqd',
      'cap_bac',
      'chuc_vu',
      'dan_toc',
      'ton_giao',
      'que_quan',
      'que_quan_chi_tiet',
      'nhom_mau',
      'so_cccd',
      'ngay_cap_cccd',
      'noi_cap_cccd',
      'so_the_bhyt',
      'so_so_bhyt',
      'noi_dang_ky_kcb',
      'ngay_han_sd_bhyt_tu',
      'ngay_han_sd_bhyt_den',
      'ghi_chu_bhyt',
    ],
  },
  {
    id: 'thong_tin_chung',
    label: 'Thông tin chung',
    icon: FileText,
    columns: ['ma_dinh_danh', 'ho_ten_thuong_dung', 'khoi_quan', 'thang_nam_nhap_ngu', 'trang_thai_xuat_ngu', 'ngay_vao_doan', 'ngay_vao_dang', 'ngay_chinh_thuc', 'so_the_dang', 'ngay_cap_the_dang', 'noi_cap_the_dang'],
  },
  {
    id: 'thong_tin_dao_tao',
    label: 'Đào tạo',
    icon: Briefcase,
    columns: ['ma_dinh_danh', 'trinh_do_van_hoa', 'trinh_do_dao_tao_cao_nhat', 'nganh_nghe_dao_tao_cao_nhat', 'nam_tot_nghiep', 'trinh_do_dt_cnqs', 'nganh_nghe_dt_cnqs', 'thang_nam_bat_dau', 'thang_nam_ket_thuc', 'ten_truong', 'nganh_hoc', 'hinh_thuc_dao_tao', 'van_bang_chung_chi'],
  },
  {
    id: 'thong_tin_nhan_than',
    label: 'Gia đình',
    icon: Users,
    columns: ['ma_dinh_danh', 'moi_quan_he', 'ho_ten', 'nam_sinh', 'nghe_nghiep', 'trang_thai', 'tinh_tp', 'xa_phuong', 'noi_o_chi_tiet'],
  },
  {
    id: 'khen_thuong',
    label: 'Khen thưởng',
    icon: Award,
    columns: ['ma_dinh_danh', 'thoi_gian', 'hinh_thuc', 'noi_dung', 'cap_quyet_dinh'],
  },
  {
    id: 'ky_luat',
    label: 'Kỷ luật',
    icon: AlertTriangle,
    columns: ['ma_dinh_danh', 'thoi_gian', 'hinh_thuc', 'noi_dung', 'cap_quyet_dinh'],
  },
  {
    id: 'luong',
    label: 'Lương & Phụ cấp',
    icon: FileText,
    columns: [
      'ma_dinh_danh',
      'tu_thang_nam',
      'den_thang_nam',
      'don_vi_cong_tac',
      'don_vi_cong_tac_chi_tiet',
      'loai_thay_doi',
      'dien_quan_ly',
      'dien_bo_tri',
      'cap_bac',
      'chuc_vu_cnqs',
      'thang_nam_dam_nhan_cnqs',
      'loai_ngach',
      'nhom',
      'bac',
      'he_so_quy_doi',
      'thang_nam_bat_dau_nhan_luong'
    ],
  },
  {
    id: 'suc_khoe',
    label: 'Sức khỏe',
    icon: Activity,
    columns: ['ma_dinh_danh', 'thoi_gian', 'phan_loai_suc_khoe', 'chieu_cao', 'can_nang', 'benh_ly', 'ghi_chu'],
  },
  {
    id: 'danh_gia_nhiem_vu',
    label: 'Đánh giá xếp loại',
    icon: Award,
    columns: ['ma_dinh_danh', 'nam', 'danh_gia_xep_loai'],
  },
  {
    id: 'nhan_dang',
    label: 'Nhận dạng',
    icon: Activity, // You can use UserCircle or similar if imported, but Activity is safe
    columns: ['ma_dinh_danh', 'chieu_cao_m', 'song_mui_ten', 'nep_tai_duoi', 'dai_tai', 'dau_vet_rieng', 'ghi_chu'],
  },
  {
    id: 'bhyt_than_nhan',
    label: 'BHYT Thân nhân',
    icon: Users,
    columns: ['ma_dinh_danh', 'ho_ten', 'moi_quan_he', 'ngay_thang_nam_sinh', 'gioi_tinh', 'dan_toc', 'ma_so_bhxh', 'so_cccd', 'noi_cap_cccd', 'noi_dang_ky_kcb', 'so_dien_thoai', 'que_quan_tinh', 'que_quan_xa', 'thuong_tru_tinh', 'thuong_tru_xa', 'ngay_han_sd_bhyt_tu', 'ngay_han_sd_bhyt_den', 'ghi_chu'],
  },
];

export const CHILD_TABLES = TABLES.filter(table => !table.isParent);

export const getTableConfig = (tableId: string) => TABLES.find(table => table.id === tableId);

export const formatFieldLabel = (key: string) => {
  const labels: Record<string, string> = {
    ma_dinh_danh: 'Mã định danh',
    ho_va_ten_khai_sinh: 'Họ và tên khai sinh',
    ngay_thang_nam_sinh: 'Ngày tháng năm sinh',
    don_vi: 'Đơn vị',
    dien_bo_tri: 'Diện bố trí',
    gioi_tinh: 'Giới tính',
    thang_nam_vao_quan_doi: 'Tháng năm vào quân đội',
    thang_nam_ve_khoa_cong_tac: 'Tháng năm về khoa công tác',
    so_cmtqd: 'Số CMTQĐ',
    ngay_cap_cmtqd: 'Ngày cấp CMTQĐ',
    noi_cap_cmtqd: 'Nơi cấp CMTQĐ',
    cap_bac: 'Cấp bậc',
    chuc_vu: 'Chức vụ',
    dan_toc: 'Dân tộc',
    ton_giao: 'Tôn giáo',
    que_quan: 'Quê quán',
    que_quan_chi_tiet: 'Quê quán chi tiết',
    nhom_mau: 'Nhóm máu',
    so_cccd: 'Số CCCD',
    ngay_cap_cccd: 'Ngày cấp CCCD',
    noi_cap_cccd: 'Nơi cấp CCCD',
    so_the_bhyt: 'Số thẻ BHYT',
    so_so_bhyt: 'Số sổ BHYT',
    noi_dang_ky_kcb: 'Nơi đăng ký KCB',
    ngay_han_sd_bhyt_tu: 'Hạn SD thẻ BHYT từ',
    ngay_han_sd_bhyt_den: 'Hạn SD thẻ BHYT đến',
    ghi_chu_bhyt: 'Ghi chú thẻ BHYT',
    ho_ten_thuong_dung: 'Họ tên thường dùng',
    khoi_quan: 'Khối quân',
    hien_tai_tinh: 'Tỉnh/Thành (chỗ ở hiện nay)',
    thang_nam_nhap_ngu: 'Tháng năm nhập ngũ',
    trang_thai_xuat_ngu: 'Trạng thái xuất ngũ',
    trinh_do_van_hoa: 'Trình độ văn hóa',
    trinh_do_dao_tao_cao_nhat: 'Trình độ đào tạo cao nhất',
    nganh_nghe_dao_tao_cao_nhat: 'Ngành nghề đào tạo cao nhất',
    nam_tot_nghiep: 'Năm tốt nghiệp',
    trinh_do_dt_cnqs: 'Trình độ ĐT CNQS',
    nganh_nghe_dt_cnqs: 'Ngành nghề ĐT CNQS',
    loai: 'Loại',
    tu_thang_nam: 'Tháng năm bắt đầu',
    den_thang_nam: 'Tháng năm kết thúc',
    bac_dao_tao: 'Bậc đào tạo',
    truong: 'Trường',
    ten_truong: 'Tên trường',
    thang_nam_bat_dau: 'Tháng năm bắt đầu',
    thang_nam_ket_thuc: 'Tháng năm kết thúc',
    nganh_hoc: 'Ngành học',
    hinh_thuc_dao_tao: 'Hình thức đào tạo',
    van_bang_chung_chi: 'Văn bằng/chứng chỉ',
    quan_he: 'Quan hệ',
    moi_quan_he: 'Mối quan hệ với QN',
    ho_va_ten: 'Họ và tên',
    ho_ten: 'Họ tên thân nhân',
    nam_sinh: 'Năm sinh',
    nghe_nghiep: 'Nghề nghiệp',
    noi_o_hien_nay: 'Nơi ở hiện nay',
    noi_o_chi_tiet: 'Địa chỉ chi tiết',
    
    // Thuong tru / Tam tru / Hien tai
    thuong_tru_tinh: 'Tỉnh/Thành (nơi thường trú)',
    thuong_tru_xa: 'Xã/Phường (nơi thường trú)',
    thuong_tru_chi_tiet: 'Địa chỉ chi tiết (nơi thường trú: Số nhà, ngõ, thôn.....)',
    tam_tru_tinh: 'Tỉnh/Thành (nơi tạm trú)',
    tam_tru_xa: 'Xã/Phường (nơi tạm trú)',
    tam_tru_chi_tiet: 'Địa chỉ chi tiết (nơi tạm trú)',
    hien_tai_xa: 'Xã/Phường (chỗ ở hiện nay)',
    hien_tai_chi_tiet: 'Địa chỉ chi tiết (chỗ ở hiện nay)',

    // Chữ viết tắt Thông tin chung
    hsq_bs_sang_qncn: 'HSQ-BS sang QNCN',
    hsq_bs_sang_cnvqp: 'HSQ-BS sang CNVQP',
    cnvqp_sang_qncn: 'CNVQP sang QNCN',
    thang_nam_tuyen_dung: 'Tháng năm tuyển dụng (VCQP, LĐHĐ, dân sự vào SQ/QNCN)',
    thang_nam_xuat_ngu: 'Tháng năm xuất ngũ',
    thang_nam_tai_ngu: 'Tháng năm tái ngũ',
    thang_nam_nhan_so: 'Tháng năm nhận sổ',
    
    // Ngay vao doan, dang
    ngay_vao_doan: 'Ngày vào Đoàn',
    ngay_vao_dang: 'Ngày vào Đảng',
    ngay_chinh_thuc: 'Ngày chính thức',
    so_the_dang: 'Số thẻ đảng',
    ngay_cap_the_dang: 'Ngày cấp thẻ đảng',
    noi_cap_the_dang: 'Nơi cấp thẻ đảng',

    xa_phuong: 'Xã phường',
    tinh_tp: 'Tỉnh TP',
    trang_thai: 'Trạng thái',
    thoi_gian: 'Thời gian',
    hinh_thuc: 'Hình thức',
    noi_dung: 'Nội dung',
    cap_quyet_dinh: 'Cấp quyết định',
    nhom: 'Nhóm',
    bac: 'Bậc',
    he_so_quy_doi: 'Hệ số quy đổi',
    he_so_bao_luu: 'Hệ số bảo lưu',
    phan_loai_suc_khoe: 'Phân loại sức khỏe',
    chieu_cao: 'Chiều cao',
    can_nang: 'Cân nặng',
    benh_ly: 'Bệnh lý',
    ghi_chu: 'Ghi chú',
    nam: 'Năm',
    danh_gia_xep_loai: 'Đánh giá xếp loại',
    chieu_cao_m: 'Chiều cao (m)',
    song_mui_ten: 'Sống mũi',
    nep_tai_duoi: 'Nếp tai dưới',
    dai_tai: 'Dái tai',
    dau_vet_rieng: 'Dấu vết riêng',
    han_dung: 'Hạn sử dụng',
    loai_cap_the: 'Loại cấp thẻ',
    ngay_cap: 'Ngày cấp',
    stt: 'STT',
    thang_nam_tham_gia_bhxh: 'Tháng năm tham gia BHXH',
    so_so_bhxh: 'Số sổ BHXH',
    che_do: 'Chế độ',
    don_vi_cong_tac: 'Đơn vị công tác',
    loai_thay_doi: 'Loại thay đổi',
    dien_quan_ly: 'Diện quản lý',
    chuc_vu_cnqs: 'Chức vụ CNQS',
    thang_nam_dam_nhan_cnqs: 'Tháng năm đảm nhận CNQS',
    tinh_tham_nien: 'Tính thâm niên',
    tinh_huong_tro_cap: 'Tính hưởng trợ cấp',
    loai_ngach: 'Loại ngạch',
    pc_tham_nien_vk: 'PC thâm niên VK',
    pc_chuc_vu: 'PC chức vụ',
    pc_tham_nien_nghe: 'PC thâm niên nghề',
    thang_nam_bat_dau_nhan_luong: 'Tháng năm bắt đầu nhận lương',
    tinh_dong_bhxh: 'Tính đóng BHXH',
    don_vi_cong_tac_chi_tiet: 'Đơn vị công tác chi tiết',
    ma_so_bhxh: 'Mã số BHXH (10 số cuối thẻ BHYT)',
    so_dien_thoai: 'Số điện thoại',
    que_quan_tinh: 'Tỉnh/Thành (Quê quán)',
    que_quan_xa: 'Xã/Phường (Quê quán)',
  };

  return labels[key] || key.replace(/_/g, ' ').replace(/(^\w|\s\w)/g, value => value.toUpperCase());
};
